version: "3"

services:
  Influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    networks:
      - mybridge
    
  Mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    depends_on:
      - "Influxdb"
    volumes:
      - ./Mosquitto/broker.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mybridge
    ports:
      - "2883:1883"
    
  Telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - "Mosquitto"
    volumes:
      - ./Telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - mybridge

  EnvironmentDataApi:
    image: environment_data_api:latest
    container_name: environment_data_api
    depends_on:
      - "Influxdb"
    environment:
      - InlfuxDB__Endpoint=http://influxdb:8086
    ports:
      - "5000:80"
    networks:
      - mybridge

  AlertService:
    image: alert_service:latest
    container_name: alert_service
    depends_on:
      - "Influxdb"
    environment:
      - InlfuxDB__Endpoint=http://influxdb:8086
    networks:
      - mybridge

  Grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./Grafana/provisioning:/etc/grafana/provisioning
      - ./Grafana/dashboards:/etc/grafana/dashboards
    networks:
      - mybridge
    ports:
      - "3000:3000"
    
    
networks:
  mybridge:
    driver: bridge
  